# Generated by Django 5.2.1 on 2025-05-26 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='productos.producto')),
                ('principio_activo', models.CharField(max_length=200)),
                ('dosis', models.CharField(max_length=100)),
                ('fecha_vencimiento', models.DateField()),
                ('venta_libre', models.BooleanField(default=True)),
            ],
            bases=('productos.producto',),
        ),
    ]
